from pydantic import BaseModel, Field
from typing import Annotated, TypedDict, List


class AlertClasification(BaseModel):
    mitre_search: bool = Field(description="True if the alert contains behaviors, commands, processes, tactics or malware. ONLY set to False if you are 100% sure that the alert does not contain any information that can be used to search in MITRE database")
    mitre_keywords: str = Field(description="The exact query to search in MITRE database. Empty if mitre_search is False")
    mitre_description: str = Field(description="Detailed description of the alert related to MITRE information. DO NOT try to identify the Technique associated, TRY to explain the context to search in the vector database. Empty if mitre_search is False")
    cve_search: bool = Field(description="True if the alert contains software versions, scan results or vulnerability identifiers. ONLY set to False if you are 100% sure that the alert does not contain any information that can be used to search in CVE database")
    cve_keywords: str = Field(description="The exact query to search in CVE database. Empty if cve_search is False")
    cve_description: str = Field(description="Detailed description of the alert related to CVE information. DO NOT try to identify the CVE associated, TRY to explain the context to search in the vector database. Empty if cve_search is False")

class AgentState(TypedDict):
    original_alert: str
    classification: AlertClasification
    mitre_data: Annotated[str, Field(description="Relevant MITRE information retrieved")]
    cve_data: Annotated[str, Field(description="Relevant CVE information retrieved")]
    final_report: Annotated[str, Field(description="Final report generated by the agent")]