from pydantic import BaseModel, Field
from typing import Annotated, TypedDict, List, Dict
from src.agent.config import AgentConfig


class AlertClasification(BaseModel):
    mitre_search: bool = Field(description="True if the alert contains behaviors, commands, processes, tactics or malware. ONLY set to False if you are 100% sure that the alert does not contain any information that can be used to search in MITRE database")
    mitre_keywords: str = Field(description="The exact query to search in MITRE database. Empty if mitre_search is False")
    mitre_description: str = Field(description="Detailed description of the alert related to MITRE information. DO NOT try to identify the Technique associated, TRY to explain the context to search in the vector database. Empty if mitre_search is False")
    cve_search: bool = Field(description="True if the alert contains software versions, scan results or vulnerability identifiers. ONLY set to False if you are 100% sure that the alert does not contain any information that can be used to search in CVE database")
    cve_keywords: str = Field(description="The exact query to search in CVE database. Empty if cve_search is False")
    cve_description: str = Field(description="Detailed description of the alert related to CVE information. DO NOT try to identify the CVE associated, TRY to explain the context to search in the vector database. Empty if cve_search is False")


class ItemEvaluation(BaseModel):
    item_id: str = Field(description="The ID of the item being evaluated (e.g., MITRE technique ID or CVE ID)")
    relevance_score: float = Field(description="A score from 0 to 1 indicating how relevant this item is to the original alert")
    explanation: str = Field(description="A detailed explanation of why this item is relevant (or not) to the alert")
    decision: bool = Field(description="True if the item is relevant and should be included in the final report, False otherwise")
    data: str = Field(description="The original data retrieved for this item. Empty if the item was not relevant and was discarded")

class ValidationReport(BaseModel):
    mitre_evaluations: List[ItemEvaluation] = Field(description="A list of evaluations for each MITRE item retrieved")
    cve_evaluations: List[ItemEvaluation] = Field(description="A list of evaluations for each CVE item retrieved")

class AgentState(TypedDict):
    original_alert: Dict
    context_window: List[str] = Field(description="A list of previous and post alerts that can provide context to the agent when analyzing the current alert. This can include previous alerts from the same source, alerts with similar characteristics, or any other relevant information that can help the agent understand the situation better.")
    
    classification: AlertClasification
    mitre_data: Annotated[str, Field(description="Relevant MITRE information retrieved")]
    cve_data: Annotated[str, Field(description="Relevant CVE information retrieved")]

    validation_report: ValidationReport = Field(description="The validation report containing evaluations for MITRE and CVE items")

    final_report: Annotated[str, Field(description="Final report generated by the agent")]

from datetime import datetime
class AlertLog(BaseModel):
    evaluation_id: str

    analysis_date: datetime = Field(default_factory=datetime.now)
    alert_id: str
    alert_timestamp: datetime
    alert_description: str

    predicted_ttps: List[str]
    # inferred_ttps: List[str]
    predicted_cves: List[str]
    # inferred_cves: List[str]

    real_ttps: List[str]
    real_cves: List[str]

    report_path: str | None = None

    execution_time: float
    token_usage: dict
    llm_calls: int
    node_breakdown: str

class EvaluationResult(BaseModel):
    evaluation_date: datetime = Field(default_factory=datetime.now)
    evaluation_id: str

    dataset_name: str
    agent_config: AgentConfig
    # agent_components: dict[str, str]

    alerts_evaluated: int

    # Metrics
    mitre_accuracy: float
    cve_accuracy: float
    total_accuracy: float

    avg_time : float
    avg_tokens: float
    avg_llm_calls: float
